Simplify m1 detection and rosetta install

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -11,8 +11,13 @@ fancy_echo() {
   printf "\n$fmt\n" "$@"
 }
 
-c1grep() {
-  grep "$@" || test $? = 1;
+fail() {
+  fancy_echo "$1"
+  exit 1
+}
+
+apple_m1() {
+  sysctl -n machdep.cpu.brand_string | grep "Apple M1"
 }
 
 # shellcheck disable=SC2154
@@ -27,41 +32,20 @@ set -euo pipefail
 #######################################################################
 
 setup_rosetta() {
-  OLDIFS=$IFS
-
-  IFS='.' read osvers_major osvers_minor osvers_dot_version <<< "$(/usr/bin/sw_vers -productVersion)"
-
-  # restore IFS to previous state
-  IFS=$OLDIFS
-
-  # Check to see if the Mac is reporting itself as running macOS 11
-  if [[ ${osvers_major} -ge 11 ]]; then
-
-    # Check to see if the Mac needs Rosetta installed by testing the processor
-    processor=$(/usr/sbin/sysctl -n machdep.cpu.brand_string | c1grep -o "Intel")
-  
-    if [[ -n "$processor" ]]; then
-      fancy_echo "$processor processor installed. No need to install Rosetta."
-    else
-      # Check Rosetta LaunchDaemon. If no LaunchDaemon is found,
-      # perform a non-interactive install of Rosetta.    
-      if [[ ! -f "/Library/Apple/System/Library/LaunchDaemons/com.apple.oahd.plist" ]]; then
-          /usr/sbin/softwareupdate --install-rosetta --agree-to-license
-        
-          if [[ $? -eq 0 ]]; then
-            fancy_echo "Rosetta has been successfully installed."
-          else
-            fancy_echo "Rosetta installation failed!"
-            exitcode=1
-          fi
+  if apple_m1; then
+    # Check Rosetta LaunchDaemon. If no LaunchDaemon is found,
+    # perform a non-interactive install of Rosetta.    
+    if [[ ! -f "/Library/Apple/System/Library/LaunchDaemons/com.apple.oahd.plist" ]]; then
+      /usr/sbin/softwareupdate --install-rosetta --agree-to-license
     
+      if [[ $? -eq 0 ]]; then
+        fancy_echo "Rosetta has been successfully installed."
       else
-        fancy_echo "Rosetta is already installed. Nothing to do."
+        fail "Rosetta installation failed!"
       fi
+    else
+      fancy_echo "Rosetta is already installed. Nothing to do."
     fi
-  else
-    fancy_echo "Mac is running macOS $osvers_major.$osvers_minor.$osvers_dot_version."
-    fancy_echo "No need to install Rosetta on this version of macOS."
   fi
 }
 
